#!/usr/bin/env python3
"""Ch5 diagnosis gallery: valid drug-like molecules generated by Tabasco's
baseline and two REPA variants (CheMeleon, MACE). All variants produce valid,
connected, drug-like molecules indistinguishably -- visual evidence that the
structural-quality surface is saturated, leaving REPA no headroom.
Output: figures/fig_ch5_gallery.png
"""

import io
import os
import sys
import numpy as np
from PIL import Image
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from rdkit import Chem  # noqa: E402
from rdkit.Chem import AllChem  # noqa: E402
from rdkit.Chem.Draw import rdMolDraw2D  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from style import use_report_style  # noqa: E402

use_report_style()
OUTDIR = os.path.join(HERE, "..")
EVAL = "/home/sr2173/git/molecular-repa/evaluation/tabasco/generation/results/geom/evaluation"
RNG = np.random.default_rng(7)
# (source label, variant dir, count)
SPEC = [
    ("Baseline", "baseline", 4),
    ("REPA: CheMeleon", "chemeleon_additive_fused", 2),
    ("REPA: MACE", "mace_additive", 2),
]


def goodmols(variant):
    sdf = os.path.join(EVAL, variant, "molecules.sdf")
    mols = [m for m in Chem.SDMolSupplier(sdf, removeHs=True) if m is not None]
    return [
        m
        for m in mols
        if len(Chem.GetMolFrags(m)) == 1 and 9 <= m.GetNumHeavyAtoms() <= 33
    ]


def draw(mol, px=360):
    AllChem.Compute2DCoords(mol)
    d = rdMolDraw2D.MolDraw2DCairo(px, px)
    d.drawOptions().bondLineWidth = 2
    d.DrawMolecule(mol)
    d.FinishDrawing()
    return np.array(Image.open(io.BytesIO(d.GetDrawingText())).convert("RGB"))


panels = []
for label, variant, n in SPEC:
    g = goodmols(variant)
    for i in RNG.permutation(len(g))[:n]:
        panels.append((label, g[i]))

fig, axes = plt.subplots(2, 4, figsize=(8.4, 4.6))
for ax, (label, m) in zip(axes.ravel(), panels):
    ax.imshow(draw(m))
    ax.axis("off")
    ax.set_title(label, fontsize=9, pad=1)
fig.tight_layout(pad=0.3)
out = os.path.join(OUTDIR, "fig_ch5_gallery.png")
fig.savefig(out, dpi=200, bbox_inches="tight")
print("wrote", out)
