"""Generate tables/table_cknna_matrix.tex --- the full model x encoder CKNNA
alignment matrix (per-residue), referenced from Ch6 S6.2.2.

Each cell is the across-layer PEAK per-residue CKNNA (bootstrap median) between a
trained model's trunk and a frozen encoder, at k=10. The point of the table is
the off-diagonal: every REPA variant raises alignment to ALL THREE encoders,
including the two it was never aligned to --- the Platonic-convergence signature
discussed in the main text. The aligned-target cell (the encoder a model was
trained against) is marked with a dagger.

Source: evaluation/proteina/alignment/results/cknna_matrix_per_residue.jsonl
(model x layer x encoder, 50-draw 80%-subsample bootstrap; step 1.0M).

Run from repo root:  python docs/masters-report/tables/scripts/make_cknna_matrix.py
"""

import json
import os
from collections import defaultdict

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
SRC = f"{ROOT}/evaluation/proteina/alignment/results/cknna_matrix_per_residue.jsonl"
OUT = f"{ROOT}/docs/masters-report/tables/table_cknna_matrix.tex"

K = 10  # nearest-neighbour count the main text reports

# encoder columns: the two alignment targets first, ESM2 (ablation-only) last
ENCODERS = [("gearnet", "GearNet"), ("mpnn", "ProteinMPNN"), ("esm2", "ESM2")]
# model rows + the encoder each was aligned to (None for baseline)
MODELS = [
    ("baseline", "Baseline", None),
    ("repa_gearnet_l4", "REPA L4-GearNet", "gearnet"),
    ("repa_gearnet_l9", "REPA L9-GearNet", "gearnet"),
    ("repa_mpnn_l4", "REPA L4-MPNN", "mpnn"),
    ("repa_mpnn_l9", "REPA L9-MPNN", "mpnn"),
]


def main():
    rows = [json.loads(line) for line in open(SRC)]
    # peak (by bootstrap median) across layers, per (model, encoder), at k=K
    best = defaultdict(lambda: (-1e9, None))
    for r in rows:
        if r.get("k") != K:
            continue
        key = (r["model"], r["encoder"])
        if r["median"] > best[key][0]:
            best[key] = (r["median"], r["layer"])

    lines = []
    lines.append(
        "% Auto-generated by tables/scripts/make_cknna_matrix.py --- do not hand-edit."
    )
    lines.append(r"\begin{table}[tbp]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\setlength{\tabcolsep}{8pt}")
    lines.append(r"\begin{tabular}{l|ccc}")
    lines.append(r"\toprule")
    lines.append(
        r" & " + " & ".join(f"\\textbf{{{disp}}}" for _, disp in ENCODERS) + r" \\"
    )
    lines.append(r"\midrule")
    for mkey, mdisp, aligned in MODELS:
        cells = []
        for ekey, _ in ENCODERS:
            val, lyr = best[(mkey, ekey)]
            txt = f"{val * 1e3:.1f}$^{{\\text{{L{lyr}}}}}$"
            if ekey == aligned:
                txt = f"{txt}$^{{\\dagger}}$"
            cells.append(txt)
        lines.append(f"{mdisp} & " + " & ".join(cells) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(
        r"\caption{\textbf{Every REPA variant raises per-residue alignment to all three "
        r"encoders, including the two it was never aligned to.} Across-layer peak per-residue "
        r"CKNNA (bootstrap median, $\times 10^{3}$), with the peak trunk layer as a superscript; "
        r"$k{=}10$, step 1.0M, $n{\le}256$ PDB-trained. The $\dagger$ marks each model's own "
        r"alignment target. Every REPA row exceeds the baseline in every column. This holds "
        r"even for the two encoders each model was never aligned to (the non-$\dagger$ cells). "
        r"We suggest the Platonic-convergence signature~\cite{PlatonicRep} as possibly being "
        r"relevant in \S\ref{sec:proteina-alignment}. "
        r"Absolute values are small (an order of magnitude below image-domain REPA), so we read "
        r"the pattern, not the magnitude. ($n{=}1$ seed; bootstrap medians.)}"
    )
    lines.append(r"\label{tab:cknna-matrix}")
    lines.append(r"\end{table}")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
