"""Generate tables/table_genrep_corr_afdb.tex --- the AFDB counterpart to
tables/table_genrep_corr.tex (Ch6 S6.2.3).

Mirrors make_genrep_corr.py exactly (same partial-Pearson-controlling-for-step
machinery, same orientation), but for AFDB-TRAINED models: representation probes
from the AFDB-trained rows of the n256_xclean_pdb_afdb sweep (n_train=1000,
seed 42), generation from the AFDB convergence sweep (FID-AFDB, designability).
This lets S6.2.3 state the rep<->gen coupling on BOTH regimes rather than PDB
only. Steps are parsed from the run-name suffix so rep and gen keys align.

Run from repo root:  python docs/masters-report/tables/scripts/make_genrep_corr_afdb.py
"""

import csv
import json
import re
import os
from collections import defaultdict
from statistics import mean

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
_REP = f"{ROOT}/evaluation/proteina/representation/results/paper"
# AFDB-trained models' probes live (at n_train=1000) in the cross-DB blinded
# sweep. IF/dihedral are blinded; CATH-A is read on the same set (no separate
# cleantrain-AFDB sweep exists), which we note in the caption.
# n1000 rows live in the main dir (early ckpts) + the _n1000_compare dir (tail
# ckpts re-evaluated 2026-06-02: GN-L9 700-1000K, GN-L4 1300K, baseline
# 1700-1800K, L4-random 100-500K). Union both; (run,step) sets are disjoint.
REP_CSVS = [
    f"{_REP}/n256_xclean_pdb_afdb/pretrained_sweep_results.csv",
    f"{_REP}/_n1000_compare/n256_xclean_pdb_afdb/pretrained_sweep_results.csv",
]


def _rep_rows():
    for path in REP_CSVS:
        if os.path.exists(path):
            yield from csv.DictReader(open(path))


GEN = f"{ROOT}/evaluation/proteina/generation/results/paper/n256_convergence_afdb/sweep_results.clean.jsonl"
OUT = f"{ROOT}/docs/masters-report/tables/table_genrep_corr_afdb.tex"

N_TRAIN = "1000"
_STEP = re.compile(r"_step(\d+)k$")


def fam(run):
    return _STEP.sub("", run)


def step_of(run):
    m = _STEP.search(run)
    return int(m.group(1)) * 1000 if m else None


def best_layer(probe_kind, col, higher_better, cath_level=None):
    """best-layer value per (family, step) for AFDB-trained runs only."""
    agg = defaultdict(list)
    for r in _rep_rows():
        run = r.get("run", "")
        if "afdb" not in run:
            continue
        if str(r.get("n_train")) != N_TRAIN:
            continue
        if (r.get("probe_seed") or "42") != "42":
            continue
        if r.get("probe_kind") != probe_kind:
            continue
        if cath_level and r.get("cath_level") != cath_level:
            continue
        v, s = r.get(col), step_of(run)
        if not v or s is None:
            continue
        try:
            agg[(fam(run), s)].append(float(v))
        except ValueError:
            continue
    return {k: (max(vs) if higher_better else min(vs)) for k, vs in agg.items()}


def gen_metric(key):
    agg = defaultdict(list)
    for line in open(GEN):
        line = line.strip()
        if not line:
            continue
        r = json.loads(line)
        run = r.get("run", "")
        v, s = r.get(key), r.get("step") or step_of(run)
        if v is None or s is None:
            continue
        agg[(fam(run), int(s))].append(v)
    return {k: mean(vs) for k, vs in agg.items()}


def pearson(xs, ys):
    mx, my = mean(xs), mean(ys)
    cov = sum((a - mx) * (b - my) for a, b in zip(xs, ys))
    vx = sum((a - mx) ** 2 for a in xs) ** 0.5
    vy = sum((b - my) ** 2 for b in ys) ** 0.5
    return cov / (vx * vy) if vx * vy else float("nan")


def partial(xs, ys, zs):
    rxy, rxz, ryz = pearson(xs, ys), pearson(xs, zs), pearson(ys, zs)
    denom = ((1 - rxz**2) * (1 - ryz**2)) ** 0.5
    return (rxy - rxz * ryz) / denom if denom else float("nan")


REP = [
    (
        "Inverse folding (top-1)",
        best_layer("inverse_folding", "if_top1_acc", True),
        True,
    ),
    ("Dihedral MAE", best_layer("dihedral", "dih_mae_total_deg", False), False),
    ("CATH-A", best_layer("cath", "cath_accuracy", True, cath_level="A"), True),
]
GEN_M = [
    ("FID", gen_metric("_res_AFDB_FID"), False),
    ("Designability", gen_metric("_res_designability_rate"), True),
]


def oriented(d, higher_better):
    return d if higher_better else {k: -v for k, v in d.items()}


cells, ns = [], []
for _, rdict, rhb in REP:
    ro = oriented(rdict, rhb)
    row = []
    for _, gdict, ghb in GEN_M:
        go = oriented(gdict, ghb)
        keys = sorted(set(ro) & set(go))
        xs, ys, zs = [ro[k] for k in keys], [go[k] for k in keys], [k[1] for k in keys]
        row.append((partial(xs, ys, zs), pearson(xs, ys), len(keys)))
    cells.append(row)
    ns.append(min(r[2] for r in row))

n_all = sorted(set(ns))
n_str = str(n_all[0]) if len(n_all) == 1 else f"{min(n_all)}--{max(n_all)}"

lines = [
    "% Auto-generated by tables/scripts/make_genrep_corr_afdb.py --- do not hand-edit."
]
lines.append("\\begin{table}[tbp]")
lines.append("\\centering")
lines.append("\\small")
lines.append("\\begin{tabular}{l" + " cc" * len(GEN_M) + "}")
lines.append("\\toprule")
group_head = ["\\textbf{Representation quality}"]
group_head += [f"\\multicolumn{{2}}{{c}}{{\\textbf{{{g[0]}}}}}" for g in GEN_M]
lines.append(" & ".join(group_head) + " \\\\")
lines.append(
    " ".join(f"\\cmidrule(lr){{{2 + 2 * j}-{3 + 2 * j}}}" for j in range(len(GEN_M)))
)
lines.append(" & ".join([""] + ["partial & raw"] * len(GEN_M)) + " \\\\")
lines.append("\\midrule")
for i, (rlabel, _, _) in enumerate(REP):
    parts = [
        f"{cells[i][j][0]:+.2f} & {cells[i][j][1]:+.2f}" for j in range(len(GEN_M))
    ]
    lines.append(f"{rlabel} & " + " & ".join(parts) + " \\\\")
lines.append("\\bottomrule")
lines.append("\\end{tabular}")
lines.append(
    "\\caption{\\textbf{On AFDB too, better trunk representations track better "
    "generation.} The AFDB counterpart to Table~\\ref{tab:proteina-genrep-corr}: partial "
    "Pearson controlling for training step (raw alongside), oriented so positive means "
    "better representation accompanies better generation. Generation is FID-AFDB and "
    "designability; representation probes are read at $n_\\text{train}{=}1000$ on the "
    "cross-database blinded set. ($n{=}" + n_str + "$ AFDB checkpoints pooled over the "
    "baseline, the REPA variants, and the random control.)}"
)
lines.append("\\label{tab:proteina-genrep-corr-afdb}")
lines.append("\\end{table}")

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Saved {OUT}  (n={n_str})")
print(f"{'rep / gen':24}", *[f"{g[0]:>20}" for g in GEN_M])
for i, (rlabel, _, _) in enumerate(REP):
    print(
        f"{rlabel:24}",
        *[
            f"  p{cells[i][j][0]:+.2f} raw{cells[i][j][1]:+.2f} (n{cells[i][j][2]})"
            for j in range(len(GEN_M))
        ],
    )
