"""Generate tables/table_rep_quality.tex --- representation rank-order at a single
late checkpoint.

We report 1.0M: the latest training step all four PDB variants share at three
probe seeds. Using ONE shared step means every variant is compared at the same
point (no cross-step confound from misaligned checkpoints), and 1.0M sits on a
representative part of the baseline trajectory. We deliberately avoid a single
1.3M point: the baseline's 1.3M checkpoint is a transient down-swing on all three
probes (CATH-A dips to 0.31 between 0.41 and 0.39 neighbours; dihedral spikes to
42 between ~31 and ~38), which would inflate every REPA delta. Persistence across
the whole of training is shown separately by Figure~\\ref{fig:proteina-rep}.

Best-layer linear probe, n_train=1000, three seeds (42/1042/2042). Baseline is
absolute; REPA rows are Delta-from-baseline. Each cell carries +/- half its seed
range. Colour marks significance against the combined (variant+baseline) seed
spread: green better (darker = column-best), red worse, uncoloured = within seed
noise. Requires \\gd/\\gb/\\rd macros from the preamble.

Run from repo root:
  python docs/masters-report/tables/scripts/make_rep_quality.py
"""

import csv
import collections
import re
import os
from statistics import mean

ROOT = "/home/sr2173/git/molecular-repa"
REP = f"{ROOT}/evaluation/proteina/representation/results/paper"
OUT = f"{ROOT}/docs/masters-report/tables/table_rep_quality_data.tex"
STEP = 1000000
N_TRAIN = "1000"

CATH = [
    f"{REP}/n256_convergence_cleantrain_pdb/pretrained_sweep_results.csv",
    f"{REP}/_n1000_compare/n256_cleantrain_pdb/pretrained_sweep_results.csv",
    f"{REP}/_n1000_bands/n256_cleantrain_pdb/pretrained_sweep_results.csv",
]
XCL = [
    f"{REP}/n256_xclean_afdb_pdb/pretrained_sweep_results.csv",
    f"{REP}/_n1000_compare/n256_xclean_afdb/pretrained_sweep_results.csv",
    f"{REP}/_n1000_bands/n256_xclean_afdb/pretrained_sweep_results.csv",
]

# display label, run family
VARS = [
    ("Baseline", "baseline_256_bs24_2gpu"),
    ("REPA L4-random", "repa_l4_256_per_residue_random_bs24_2gpu"),
    ("REPA L9-GearNet", "repa_l9_256_per_residue_bs24_2gpu"),
    ("REPA L9-MPNN", "repa_mpnn_l9_256_per_residue"),
]

# csvs, probe_kind, value col, cath level, higher_better, precision
METR = [
    (XCL, "inverse_folding", "if_top1_acc", None, True, 3),
    (XCL, "dihedral", "dih_mae_total_deg", None, False, 1),
    (CATH, "cath", "cath_accuracy", "C", True, 3),
    (CATH, "cath", "cath_accuracy", "A", True, 3),
    (CATH, "cath", "cath_accuracy", "T", True, 3),
]


def fam(run):
    return re.sub(r"_step\d+k$", "", str(run))


def cell_stats(csvs, kind, col, level, higher, run):
    by = collections.defaultdict(list)  # seed -> [layer values]
    for p in csvs:
        if not os.path.exists(p):
            continue
        for r in csv.DictReader(open(p)):
            if str(r.get("n_train")) != N_TRAIN or r.get("probe_kind") != kind:
                continue
            if level and r.get("cath_level") != level:
                continue
            if fam(r["run"]) != run or int(r["step"]) != STEP:
                continue
            v = r.get(col)
            if v:
                by[r.get("probe_seed") or "42"].append(float(v))
    per = [(max(v) if higher else min(v)) for v in by.values()]
    if not per:
        return None
    return (mean(per), (max(per) - min(per)) / 2.0, len(per))


data = {}  # (metric_idx, run) -> (mean, half, n)
for j, m in enumerate(METR):
    for _, run in VARS:
        data[(j, run)] = cell_stats(m[0], m[1], m[2], m[3], m[4], run)

# sanity: the published-known values must reconstruct
b_a = data[(3, "baseline_256_bs24_2gpu")][0]
gn_a = data[(3, "repa_l9_256_per_residue_bs24_2gpu")][0]
assert abs(b_a - 0.408) < 0.01, b_a
assert abs((gn_a - b_a) - 0.267) < 0.01, gn_a - b_a


def fnum(x, prec):
    return f"{x:.{prec}f}"


def fdelta(x, prec):
    return f"{'+' if x >= 0 else '-'}{abs(x):.{prec}f}"


base_run = VARS[0][1]
lines = [
    "% Numbers generated by tables/scripts/make_rep_quality.py --- safe to overwrite.",
    "% The caption and table environment are hand-maintained in table_rep_quality.tex.",
    "\\begin{tabular}{lccccc}",
    "\\toprule",
    " & & & \\multicolumn{3}{c}{\\textbf{CATH top-1 acc.\\,$\\uparrow$}} \\\\",
    "\\cmidrule(lr){4-6}",
    "\\textbf{Variant} & \\textbf{IF top-1\\,$\\uparrow$} "
    "& \\textbf{dihedral MAE\\,(\\,$^\\circ$\\,)\\,$\\downarrow$} & C & A & T \\\\",
    "\\midrule",
]

for name, run in VARS:
    cells = []
    for j, m in enumerate(METR):
        prec, higher = m[5], m[4]
        st = data[(j, run)]
        if st is None:
            cells.append("---")
            continue
        mn, half, _ = st
        if name == "Baseline":
            cells.append(f"${fnum(mn, prec)}_{{\\pm{fnum(half, prec)}}}$")
            continue
        bmn, bhalf, _ = data[(j, base_run)]
        delta = mn - bmn
        improving = (delta > 0) if higher else (delta < 0)
        sig = abs(delta) > (half + bhalf)
        best = True
        for _, run2 in VARS[1:]:
            if run2 == run:
                continue
            st2 = data[(j, run2)]
            if not st2:
                continue
            d2 = st2[0] - bmn
            imp2 = (d2 > 0) if higher else (d2 < 0)
            if imp2 and abs(d2) > abs(delta):
                best = False
        txt = f"${fdelta(delta, prec)}_{{\\pm{fnum(half, prec)}}}$"
        if sig and improving:
            cells.append(f"\\gb{{{txt}}}" if best else f"\\gd{{{txt}}}")
        elif sig and not improving:
            cells.append(f"\\rd{{{txt}}}")
        else:
            cells.append(txt)
    lines.append(f"{name} & " + " & ".join(cells) + " \\\\")

lines += [
    "\\bottomrule",
    "\\end{tabular}",
]

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT)
print("\n".join(lines))
