"""Generate tables/table_rep_quality_full.tex --- the FULL six-variant PDB
representation-quality ablation (Appendix), at a single late checkpoint.

Same recipe as the main-text table (make_rep_quality.py): step 1.0M, the latest
training step the multi-seed variants share, compared at one shared step rather
than a window. Extends the four-row main table with the remaining encoder x depth
combinations (L4-GearNet, L4-MPNN). Those two were only ever probed at a single
seed, so they carry no seed range and are marked with a dagger; the other four
rows are 3-seed. We avoid a 1.3M point because baseline@1.3M is a transient
down-swing on all probes (see make_rep_quality.py).

Best-layer linear probe, n_train=1000. Baseline absolute; REPA rows are
Delta-from-baseline, with +/- half the seed range where >1 seed exists. Colour
marks significance against the combined seed spread (single-seed rows use the
baseline spread alone): green better (darker = column-best), red worse,
uncoloured = within seed noise. IF/dihedral on the cross-database blinded set,
CATH on the cleantrain set. Requires \\gd/\\gb/\\rd macros.

Run from repo root:
  python docs/masters-report/tables/scripts/make_rep_quality_full.py
"""

import csv
import collections
import re
import os
from statistics import mean

ROOT = "/home/sr2173/git/molecular-repa"
REP = f"{ROOT}/evaluation/proteina/representation/results/paper"
OUT = f"{ROOT}/docs/masters-report/tables/table_rep_quality_full_data.tex"
STEP = 1000000
N_TRAIN = "1000"

CATH = [
    f"{REP}/n256_convergence_cleantrain_pdb/pretrained_sweep_results.csv",
    f"{REP}/_n1000_compare/n256_cleantrain_pdb/pretrained_sweep_results.csv",
    f"{REP}/_n1000_bands/n256_cleantrain_pdb/pretrained_sweep_results.csv",
]
XCL = [
    f"{REP}/n256_xclean_afdb_pdb/pretrained_sweep_results.csv",
    f"{REP}/_n1000_compare/n256_xclean_afdb/pretrained_sweep_results.csv",
    f"{REP}/_n1000_bands/n256_xclean_afdb/pretrained_sweep_results.csv",
]

VARS = [
    ("Baseline", "baseline_256_bs24_2gpu"),
    ("REPA L4-random", "repa_l4_256_per_residue_random_bs24_2gpu"),
    ("REPA L4-GearNet", "repa_l4_256_per_residue_bs24_2gpu"),
    ("REPA L4-MPNN", "repa_mpnn_l4_256_per_residue"),
    ("REPA L9-GearNet", "repa_l9_256_per_residue_bs24_2gpu"),
    ("REPA L9-MPNN", "repa_mpnn_l9_256_per_residue"),
]
METR = [
    (XCL, "inverse_folding", "if_top1_acc", None, True, 3),
    (XCL, "dihedral", "dih_mae_total_deg", None, False, 1),
    (CATH, "cath", "cath_accuracy", "C", True, 3),
    (CATH, "cath", "cath_accuracy", "A", True, 3),
    (CATH, "cath", "cath_accuracy", "T", True, 3),
]


def fam(run):
    return re.sub(r"_step\d+k$", "", str(run))


def cell_stats(csvs, kind, col, level, higher, run):
    by = collections.defaultdict(list)
    for p in csvs:
        if not os.path.exists(p):
            continue
        for r in csv.DictReader(open(p)):
            if str(r.get("n_train")) != N_TRAIN or r.get("probe_kind") != kind:
                continue
            if level and r.get("cath_level") != level:
                continue
            if fam(r["run"]) != run or int(r["step"]) != STEP:
                continue
            v = r.get(col)
            if v:
                by[r.get("probe_seed") or "42"].append(float(v))
    per = [(max(v) if higher else min(v)) for v in by.values()]
    if not per:
        return None
    return (mean(per), (max(per) - min(per)) / 2.0, len(per))


data = {}
for j, m in enumerate(METR):
    for _, run in VARS:
        data[(j, run)] = cell_stats(m[0], m[1], m[2], m[3], m[4], run)

# sanity: trained-L4 must beat random-L4 on CATH-A (the table's key claim)
l4gn = data[(3, "repa_l4_256_per_residue_bs24_2gpu")][0]
l4rnd = data[(3, "repa_l4_256_per_residue_random_bs24_2gpu")][0]
assert l4gn > l4rnd, (l4gn, l4rnd)


def fnum(x, prec):
    return f"{x:.{prec}f}"


def fdelta(x, prec):
    return f"{'+' if x >= 0 else '-'}{abs(x):.{prec}f}"


base_run = VARS[0][1]
single_seed = []
lines = [
    "% Numbers generated by tables/scripts/make_rep_quality_full.py --- safe to overwrite.",
    "% The caption and table environment are hand-maintained in table_rep_quality_full.tex.",
    "\\begin{tabular}{lccccc}",
    "\\toprule",
    " & & & \\multicolumn{3}{c}{\\textbf{CATH top-1 acc.\\,$\\uparrow$}} \\\\",
    "\\cmidrule(lr){4-6}",
    "\\textbf{Variant} & \\textbf{IF top-1\\,$\\uparrow$} "
    "& \\textbf{dihedral MAE\\,(\\,$^\\circ$\\,)\\,$\\downarrow$} & C & A & T \\\\",
    "\\midrule",
]

for name, run in VARS:
    nseed = max(
        (data[(j, run)][2] for j in range(len(METR)) if data[(j, run)]), default=0
    )
    label = name + ("$^{\\dagger}$" if 0 < nseed < 2 else "")
    if 0 < nseed < 2 and name != "Baseline":
        single_seed.append(name.replace("REPA ", ""))
    cells = []
    for j, m in enumerate(METR):
        prec, higher = m[5], m[4]
        st = data[(j, run)]
        if st is None:
            cells.append("---")
            continue
        mn, half, n = st
        if name == "Baseline":
            cells.append(f"${fnum(mn, prec)}_{{\\pm{fnum(half, prec)}}}$")
            continue
        bmn, bhalf, _ = data[(j, base_run)]
        delta = mn - bmn
        improving = (delta > 0) if higher else (delta < 0)
        sig = abs(delta) > (half + bhalf)
        best = True
        for _, run2 in VARS[1:]:
            if run2 == run or not data[(j, run2)]:
                continue
            d2 = data[(j, run2)][0] - bmn
            imp2 = (d2 > 0) if higher else (d2 < 0)
            if imp2 and abs(d2) > abs(delta):
                best = False
        sub = f"_{{\\pm{fnum(half, prec)}}}" if n >= 2 else ""
        txt = f"${fdelta(delta, prec)}{sub}$"
        if sig and improving:
            cells.append(f"\\gb{{{txt}}}" if best else f"\\gd{{{txt}}}")
        elif sig and not improving:
            cells.append(f"\\rd{{{txt}}}")
        else:
            cells.append(txt)
    lines.append(f"{label} & " + " & ".join(cells) + " \\\\")

# `dagger` is the single-seed caption annotation. The caption now lives in the
# hand-maintained wrapper (table_rep_quality_full.tex), so this is unused in the
# emitted data file --- kept for reference / parity with the wrapper caption.
dagger = (
    " ($^{\\dagger}$%s single-seed.)" % " and ".join(single_seed) if single_seed else ""
)
lines += [
    "\\bottomrule",
    "\\end{tabular}",
]

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT, "| single-seed rows:", single_seed)
print("\n".join(lines))
