"""Generate tables/table_13m_ranges.tex --- the per-seed min--max spread behind
the 1.3M centerpiece table (Table~\\ref{tab:proteina-13m}).

Each cell of the centerpiece reports a mean over generation seeds (42/1042/2042
at the default sde_n0.45 sampler). This appendix table reports, for the same
cells, the min--max range across those seeds, so a reader can judge which small
deltas in the centerpiece are within seed scatter. Absolute values (the
centerpiece shows REPA rows as deltas; ranges of deltas are not interpretable).

Two rows are single-seed (PDB L9-GearNet, AFDB L4-MPNN) and show one value, no
range. The mapping (run family + step per row) is verified by reconstructing the
centerpiece mean per cell; see the assert block.

Run from repo root:
  python docs/masters-report/tables/scripts/make_13m_ranges.py
"""

import json
import glob
import re
import collections
import statistics as st

ROOT = "/home/sr2173/git/molecular-repa"
GEN = f"{ROOT}/evaluation/proteina/generation/results"
OUT = f"{ROOT}/docs/masters-report/tables/table_13m_ranges.tex"

# display -> (pdb_key, afdb_key, precision)
METRICS = [
    ("Des", "_res_designability_rate", "_res_designability_rate", 2),
    ("FPSD", "_res_PDB_FID", "_res_AFDB_FID", 0),
    ("fJSD-A", "_res_PDB_fJSD_A", "_res_AFDB_fJSD_A", 2),
    ("fS-A", "_res_fS_A", "_res_fS_A", 2),
    ("pwTM", "_res_diversity_pairwise_tm_mean", "_res_diversity_pairwise_tm_mean", 2),
    ("ssJSD2D (W)", "_res_ss_jsd_pdb_2d", "_res_ss_jsd_afdb_2d", 2),
    (
        "ssJSD2D (D)",
        "_res_ss_jsd_pdb_designable_2d",
        "_res_ss_jsd_afdb_designable_2d",
        2,
    ),
    (r"$\beta$\%", "_res_ss_frac_E_designable", "_res_ss_frac_E_designable", 2),
]

# (regime, label, family, step)
ROWS = [
    ("PDB", "Baseline", "baseline_256_bs24_2gpu", 1300000),
    ("PDB", "REPA L4-random", "repa_l4_256_per_residue_random_bs24_2gpu", 1200000),
    ("PDB", "REPA L4-GearNet", "repa_l4_256_per_residue_bs24_2gpu", 1000000),
    ("PDB", "REPA L9-GearNet", "repa_l9_256_per_residue_bs24_2gpu", 1300000),
    ("PDB", "REPA L4-MPNN", "repa_mpnn_l4_256_per_residue", 1300000),
    ("PDB", "REPA L9-MPNN", "repa_mpnn_l9_256_per_residue", 1300000),
    ("AFDB", "Baseline", "baseline_afdb_256", 1300000),
    ("AFDB", "REPA L4-random", "repa_l4_afdb_256_random", 500000),
    ("AFDB", "REPA L4-GearNet", "repa_l4_afdb_256", 1300000),
    ("AFDB", "REPA L9-GearNet", "repa_l9_afdb_256", 1000000),
    ("AFDB", "REPA L4-MPNN", "repa_mpnn_l4_afdb_256", 1100000),
    ("AFDB", "REPA L9-MPNN", "repa_mpnn_l9_afdb_256", 1300000),
]

# step tag printed after a variant whose checkpoint is not at 1.3M
STEP_TAG = {1000000: "1.0M", 1100000: "1.1M", 1200000: "1.2M", 500000: "0.5M"}

# published centerpiece means for the reconstruction check (Des, FPSD, pwTM abs)
BASE = {
    "PDB": dict(Des=0.56, FPSD=416, pwTM=0.16),
    "AFDB": dict(Des=0.64, FPSD=386, pwTM=0.18),
}
PUB = {
    ("PDB", "Baseline"): (0.56, 416, 0.16),
    ("PDB", "REPA L4-random"): (0.24, 437, 0.19),
    ("PDB", "REPA L4-GearNet"): (0.46, 433, 0.17),
    ("PDB", "REPA L9-GearNet"): (0.49, 394, 0.28),
    ("PDB", "REPA L4-MPNN"): (0.62, 489, 0.24),
    ("PDB", "REPA L9-MPNN"): (0.78, 387, 0.28),
    ("AFDB", "Baseline"): (0.64, 386, 0.18),
    ("AFDB", "REPA L4-random"): (0.85, 371, 0.19),
    ("AFDB", "REPA L4-GearNet"): (0.75, 315, 0.20),
    ("AFDB", "REPA L9-GearNet"): (0.72, 293, 0.25),
    ("AFDB", "REPA L4-MPNN"): (0.69, 458, 0.25),
    ("AFDB", "REPA L9-MPNN"): (0.76, 387, 0.18),
}


def fam_step(run):
    m = re.match(r"(.*)_step(\d+)k$", run)
    return (m.group(1), int(m.group(2)) * 1000) if m else (run, None)


ALL_KEYS = set()
for _, pk, ak, _ in METRICS:
    ALL_KEYS |= {pk, ak}

store = collections.defaultdict(dict)
for fn in glob.glob(f"{GEN}/**/sweep_results.jsonl", recursive=True):
    for line in open(fn):
        if not line.strip():
            continue
        try:
            r = json.loads(line)
        except json.JSONDecodeError:
            continue
        if r.get("sampler_tag") not in (None, "sde_n0.45"):
            continue
        if r.get("_res_diversity_pairwise_tm_mean") is None:
            continue
        fam, step = fam_step(str(r.get("run", "")))
        seed = r.get("seed")
        if seed is None:
            continue
        for mk in ALL_KEYS:
            if r.get(mk) is not None:
                store[(fam, step, seed)].setdefault(mk, r[mk])


def fmt(v, prec):
    return f"{v:.{prec}f}"


def cell(vals, prec):
    if not vals:
        return "---"
    lo, hi = min(vals), max(vals)
    if len(vals) == 1 or lo == hi:
        return fmt(lo, prec)
    return f"{fmt(lo, prec)}--{fmt(hi, prec)}"


lines = [
    "% Auto-generated by tables/scripts/make_13m_ranges.py --- do not hand-edit.",
    "% Per-seed min--max spread behind Table~\\ref{tab:proteina-13m}.",
    "\\begin{table}[tbp]",
    "\\centering",
    "\\scriptsize",
    "\\setlength{\\tabcolsep}{4pt}",
    "\\resizebox{\\textwidth}{!}{%",
    "\\begin{tabular}{l" + "c" * len(METRICS) + "}",
    "\\toprule",
    "\\textbf{Variant (range over seeds)} & "
    + " & ".join(m[0] for m in METRICS)
    + " \\\\",
    "\\midrule",
]

for regime in ("PDB", "AFDB"):
    lines.append(
        "\\multicolumn{%d}{l}{\\textit{%s-trained}}\\\\" % (len(METRICS) + 1, regime)
    )
    for rg, label, fam, step in ROWS:
        if rg != regime:
            continue
        seeds = sorted(s for (f, st_, s) in store if f == fam and st_ == step)

        # verification
        def col(mk):
            return [
                store[(fam, step, s)].get(mk)
                for s in seeds
                if store[(fam, step, s)].get(mk) is not None
            ]

        des = st.mean(col("_res_designability_rate"))
        fid_key = "_res_PDB_FID" if regime == "PDB" else "_res_AFDB_FID"
        fid = st.mean(col(fid_key))
        pw = st.mean(col("_res_diversity_pairwise_tm_mean"))
        pdes, pfid, ppw = PUB[(regime, label)]
        assert abs(des - pdes) < 0.02, f"{regime} {label} Des {des:.3f} vs {pdes}"
        assert abs(fid - pfid) < 3, f"{regime} {label} FPSD {fid:.1f} vs {pfid}"
        assert abs(pw - ppw) < 0.01, f"{regime} {label} pwTM {pw:.3f} vs {ppw}"
        name = label
        tag = STEP_TAG.get(step)
        if tag:
            name += f" \\textit{{\\scriptsize({tag})}}"
        if len(seeds) == 1:
            name += "$^{\\dagger}$"
        cells = []
        for disp, pk, ak, prec in METRICS:
            mk = pk if regime == "PDB" else ak
            cells.append(cell(col(mk), prec))
        lines.append(name + " & " + " & ".join(cells) + " \\\\")
    if regime == "PDB":
        lines.append("\\midrule")

lines += [
    "\\bottomrule",
    "\\end{tabular}}",
    "\\caption{\\textbf{Per-seed min--max spread behind the 1.3M centerpiece "
    "(Table~\\ref{tab:proteina-13m}).} For each cell the centerpiece reports the "
    "mean over generation seeds (42/1042/2042, default sde sampler $n{=}0.45$); "
    "here we give the min--max range across those seeds, in absolute units. This "
    "lets the reader gauge which small centerpiece deltas sit within seed scatter "
    "--- e.g.\\ the AFDB L4-GearNet designable-diversity (pwTM) range overlaps the "
    "baseline's, while its FPSD range is cleanly separated. Columns match the "
    "centerpiece: T-W is (fJSD-A, fS-A), T-D is pwTM, S-W is ssJSD2D~(W), S-D is "
    "ssJSD2D~(D) and $\\beta$\\%. ($^{\\dagger}$single seed, no range.)}",
    "\\label{tab:proteina-13m-ranges}",
    "\\end{table}",
]

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT)
print("\n".join(lines))
